#! /bin/sh

# based on: https://github.com/cdown/passmenu

# modifications of this script are by: Jason W Ryan
# see official repository: https://bitbucket.org/jasonwryan/shiv

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR:-~/.password-store}
files=( "$prefix"/**/*.gpg )
files=( "${files[@]#"$prefix"/}" )
files=( "${files[@]%.gpg}" )
fbase=( "${files[@]##*/}" )

word=$(printf '%s\n' "${fbase[@]}" | dmenu "$@")

if [[ -n $word ]]; then
	for match in "${files[@]}"; do 
		if [[ $word == ${match#*/} ]]; then
			/usr/bin/pass show -c "$match" 2>/dev/null
		fi
	done
fi
