#!/bin/bash

if (( $# != 1 )); then
	printf "%s\n" "Please provide the name of your window manager"
        exit 1
fi	

case $1 in
	  i3)
		:
		;;
	sway)
		:
		;;
	   *)
		printf "%s\n" "This script does not support that window manager!"
		;;

esac

export TERM=st-256color
export XKB_DEFAULT_OPTIONS=caps:escape
export GDK_BACKEND=x11

if [[ "$XDG_RUNTIME_DIR" == "" ]]
then
	export XDG_RUNTIME_DIR=/tmp
fi

export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pictures"
export XDG_VIDEOS_DIR="$HOME/videos"

if [[ $1 ==  "sway" ]]; then
	msg="${1}msg"
else
	msg="${1}-msg"
fi

# TODO:// Maybe add wallpaper(slider) script here forked to the background with timer?

if [[ $2 == "debug" ]]; then
	:
	# TODO:// Add debug config here, maybe read from build files in repository?
else
	/usr/bin/$1 2> ~/${1}.log
fi
